### ISSUE TITLE
WARNING: Calling str(pkt) on Python 3 makes no sense!

### ISSUE THREAD

**Issue by notcreeperdude** [HerrEurobeat/csgo-overwatch-downloader#1]
![image](https://user-images.githubusercontent.com/75228915/123016441-82697e80-d3c2-11eb-98c2-79206dbab2e2.png)

**Comment by 3urobeat** [comment]
Hey!  
More information would be helpful. Does it still detect and download the OW demo?  
This is just a warning, not an error. I can replicate it on Python 3.9.5 but I can't download any OW demos right now as I don't have any rank because of inactivity.

**Comment by notcreeperdude** [comment]
Oh my bad, i thought i closed this becuasse i realised i was being an absolute moron. Thank you anyway :)

**Comment by 3urobeat** [comment]
No worries  
Seems like I found what was causing the warning. Could you maybe please test these changes for me? (just replace the new downloader.py with the one on your pc and see if it recognizes and downloads the demo)  
I sadly don't have a rank atm and therefore can't download OW demos...

**Comment by 3urobeat** [comment]
Nvm, was able to test the changes by finding a demo download link online and then trying to start a download in my browser manually.  
Made a few more fixes and everything should work now fine again but without that warning.
